### PR TITLE
Remove DB access & specific setup tweaks

### PR DESCRIPTION
**Pull request by AetherUnbound**
This PR removes the access limits on the database, along with restricting external access to the database. These restrictions were put in place so that we could prevent external actors from messing with the database. I'm not sure anyone is using direct access to this database anyway, so I'd rather just do away with the extra steps (they were also causing me some trouble locally for reasons unknown). I've removed the port forwarding from the postgres container so it's no longer accessible outside the docker network.

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM as long as we're sure it's safe 😅 as far as I can tell it is.

**Comment by AetherUnbound** [comment]
I'm shutting off _all_ external access outside the docker network, so if someone gets into this database we'll have bigger concerns :joy: also its state is pretty much built into the docker image so we can just restart it to wipe it clean.

**Comment by mpuckett159** [comment]
Yeah this is the right move, should have axed it sooner honestly. LGTM

**Review by mpuckett159 — APPROVED** [review]
👍

**Review by seattle-n — APPROVED** [review]
Thanks, I was having the same issue and this is a lot like the change I’d made locally to fix it, ha.

**Comment by AetherUnbound** [comment]
Incidentally, we weren't even forwarding the port on our server so no one could access it anyway :clown_face:

**Pull request merged**
