### PR TITLE
Add 12/29/2021 roster

### PR DESCRIPTION
**Pull request by mpuckett159**

### CODE REVIEW

**Comment by AetherUnbound** [comment]
I'm seeing deletions, was this replacing an existing roster?

**Comment by mpuckett159** [comment]
Uh oh, it shouldn't have been. That's not good. Let me figure out what happened.

**Comment by AetherUnbound** [comment]
I'm willing to bet it's a line ending thing...lol

**Comment by mpuckett159** [comment]
Ok doing some checks:
```
>>> import pandas as pd
>>> df1 = pd.read_csv("Seattle-WA-Police-Department_Historical-main.csv")
>>> df2 = pd.read_csv("Seattle-WA-Police-Department_Historical-update.csv")
>>> len(df1["date"].unique())
107
>>> len(df2["date"].unique())
108
```
So we know that there's one more unique date.

```
>>> len(df1["date"])
198669
>>> len(df2["date"])
200382
>>> len(df2.loc[df2["date"] == "2021-12-29"])
1713
>>> 200382 - 198669
1713
```
So the difference between the number of records in the main csv and this branch's csv is equal to the number of records where the date is for the new roster.

I think you were right this is a CRLF vs LF issue. I did the merge on my desktop so it must have introduced something there. Either way the dos2unix hack I put in should take care of it.

**Comment by AetherUnbound** [comment]
Hope it's OK, I just fixed them as part of this PR for posterity and easier diffing.

**Review by AetherUnbound — APPROVED** [review]

**Comment by mpuckett159** [comment]
Ah nice, I tried to fix it myself but I couldn't get it to work, glad you were able to.

**Pull request merged**
